# Generated by Django 5.1.2 on 2024-10-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Cliente')),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos del Cliente')),
                ('telefono', models.CharField(blank=True, default='3', max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
            options={
                'verbose_name': 'cliente',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(default='', max_length=50)),
                ('tipo_producto', models.CharField(default='Tipo', max_length=35)),
                ('precio_producto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion_producto', models.CharField(blank=True, default='Desc', max_length=150, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'producto',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ingreso_producto',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('add_Cantidad_producto', models.IntegerField(default=0)),
                ('fecha_add', models.DateField(auto_now=True)),
                ('nombre_alimentador', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Proy.producto')),
            ],
            options={
                'verbose_name': 'Inventario de Producto',
                'db_table': 'ingreso_producto',
            },
        ),
        migrations.CreateModel(
            name='carrito_ventas',
            fields=[
                ('id_carrito_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('unidades_vendidas', models.PositiveIntegerField(default=0)),
                ('precio', models.BigIntegerField(default=0, verbose_name='Precio_carrito')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Proy.producto')),
            ],
            options={
                'verbose_name': 'Carrito_ventas',
                'db_table': 'carrito_ventas',
            },
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now=True, verbose_name='Fecha de la Venta')),
                ('nombre_vendedor', models.CharField(max_length=20)),
                ('Producto', models.ManyToManyField(blank=True, through='App_Proy.carrito_ventas', to='App_Proy.producto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Proy.cliente')),
            ],
            options={
                'verbose_name': 'venta',
                'db_table': 'venta',
            },
        ),
        migrations.AddField(
            model_name='carrito_ventas',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Proy.venta'),
        ),
    ]
